#!/bin/bash
# This hook is sourced before every virtualenv is deactivated.

. $V/libvw

cd $HOME
unset PROMPT_COMMAND
cd $OLDCURDIR
export PS1=$OLDPS1


if [[ ! -f $H/.nopg ]] ;
then
    anyone=$( fuser $H 2> /dev/null | cut -d":" -f2 )

    if [[ "$anyone" == "" ]];
    then
        echo "stopping postgres instance: $THIS" &&
            [[ -f $PGDATA/postmaster.pid  ]] &&
            kill -2 $( cat $PGDATA/postmaster.pid | head -n 1 )
    fi
fi


